ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Install Zen Browser
COPY ./src/ubuntu/install/zen/ $INST_SCRIPTS/zen/
COPY ./src/ubuntu/install/zen/zen.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/zen/install_zen.sh && rm -rf $INST_SCRIPTS/zen/

# Preinstall extensions (uBlock Origin, Dark Reader)
COPY ./src/ubuntu/install/zen/ $INST_SCRIPTS/zen/
RUN bash $INST_SCRIPTS/zen/install_extensions.sh && rm -rf $INST_SCRIPTS/zen/

# Install Russian Trusted Root CA (Минцифры)
COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

# Use a dark GTK/xfwm4 theme so the window titlebar matches the browser
RUN sed -i 's|<property name="theme" type="string" value="Default"/>|<property name="theme" type="string" value="Greybird-dark"/>|' \
      $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml \
    && sed -i 's|<property name="ThemeName" type="empty"/>|<property name="ThemeName" type="string" value="Greybird-dark"/>|' \
      $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

# Security modifications
COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/

# Setup the custom startup script that will be invoked when the container starts
#ENV LAUNCH_URL  http://kasmweb.com

COPY ./src/ubuntu/install/zen/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh

ENV KASM_RESTRICTED_FILE_CHOOSER=1
COPY ./src/ubuntu/install/gtk/ $INST_SCRIPTS/gtk/
RUN bash $INST_SCRIPTS/gtk/install_restricted_file_chooser.sh
COPY ./src/ubuntu/install/close_browser_breakout_via_file_manager/ $INST_SCRIPTS/close_browser_breakout_via_file_manager/
RUN bash $INST_SCRIPTS/close_browser_breakout_via_file_manager/replace_thunar_with_empty_script.sh

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000